import type { QianjiControlRecoveryCliOptions } from "./qianji-control-recovery-policy.js";

export type PiWendaoCliOptionsDto = QianjiControlRecoveryCliOptions & {
  process?: string;
  instanceId?: string;
  startAtNode?: string;
  workflowStartMode?: string;
  qianji?: string;
  qianjiClient?: string;
  flowhubScenario?: string;
  flowhubRoot?: string;
  dmn?: string[];
  hostFixture?: string;
  eventFixture?: string;
  contextJson?: string;
  traceFrameMs?: number;
  model?: string;
  provider?: string;
  apiKey?: string;
  thinking?: string;
  extension?: string[];
  var?: string[];
  show?: boolean;
  graph?: boolean;
  cancel?: boolean;
  tui?: boolean;
  search?: string;
  wendaoGraph?: string;
  searchJulia?: string;
  searchBackend?: string;
  searchRustWorkspace?: string;
  searchRustCommand?: string;
  searchRustBridgeBin?: string;
  searchRustBridgeSession?: boolean;
  searchFlightBaseUrl?: string;
  searchFlightTimeoutSeconds?: number;
  searchStrategyFlowServiceBaseUrl?: string;
  searchStrategyFlowServiceTimeoutSeconds?: number;
  searchAgent?: boolean;
  searchAgentAnswerRequest?: string;
  searchAgentAnswerMode?: string;
  searchAgentAnswerChunkSize?: number;
  searchAgentAnswerResume?: boolean;
  searchAgentAnswerEvidence?: string;
  searchJson?: boolean;
  serverlessMemoryRecallJson?: string;
};
